[package]
name = "sleek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
image = "0.24.2"
x11 = {version = "2.19.1", features = ["xlib", "xrandr"]}